name: Web App CI/CD
run-name: Running CI/CD for our web application ğŸš€
on:
    push:
        branches:
            - first_implementation_cicd
        paths:
            - "web_solution/**"
jobs:
    # Create job for checking out the repository and executing unit tests with pytest
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r web_solution/requirements-test.txt
            - name: Run unit tests
              run: |
                  pytest web_solution/tests/
    # Create a job for building and pushing the Docker image
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: unit-tests
        steps:
            - name: Test failing tests
              run: |
                  echo "This should not run because unit test failed"
            # - name: Check out repository code
            #   uses: actions/checkout@v4
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v1
            # - name: Login to Docker Hub
            #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            # - name: Build and push Docker image
            #   run: |
            #       docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest web_solution/
            #       docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - run: echo "ğŸ’¡ This is a very chingona feature."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
